# Generated by Django 4.1.7 on 2023-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='not_available', max_length=70),
        ),
    ]
